version: '3.4'

services:
  app:
    image: 'school-db:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db

  db:
    image: 'postgres:14-alpine'
    container_name: school_db_sh1rsh1n
    environment:
      - POSTGRES_USER=pg_root
      - POSTGRES_PASSWORD=pg_1amAccept
      - POSTGRES_DB=school_db
    ports:
      - '5432:5432'