version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    container_name: school_db_postgres
    environment:
      POSTGRES_DB: "school_db"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"